openapi: 3.0.3
info:
  title: Главный Интерфейс (API)
  version: 0.0.1
  
servers:
  - url: https://api.dev.petstore/v1
    description: Тестовая среда
  - url: https://api.prod.petstore/v1
    description: Рабочая среда

security:
  - ApiKeyAuth: []

paths: {}

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
