openapi: 3.0.3
info:
  title: Главный Интерфейс (API)
  version: 1.0.0
  description: Тестовая спецификация для управления питомцами
  
servers:
  - url: https://api.dev.petstore/v1
    description: Тестовая среда
  - url: https://api.prod.petstore/v1
    description: Рабочая среда


paths:
  /pets:
    get:
      summary: Get pets list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

paths: {}
