openapi: 3.0.3
info:
  title: Главный Интерфейс (API)
  version: 1.0.0
  description: Тестовая спецификация для управления питомцами
  
servers:
  - url: https://api.dev.petstore/v1
    description: Тестовая среда
  - url: https://api.prod.petstore/v1
    description: Рабочая среда

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

paths: {}
